### PR TITLE
Add tooltip component

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
- Add tooltip component

### QA
- Check the tooltip component at the bottom of the demo

### CODE REVIEW

**Comment by richmccartney** [comment]
@anthonydillon Works really well I've done something similar on MAAS, few things I think this should be a utility class as this could be used on any sort of element with in the Cloud theme.

Secondly what are you thoughts on removing the ```.tooltip__content``` element, the singular class itself could facilitate the need and then be able to use modifiers on it e.g ```.u-tooltip--left``` if we needed a position left style tooltip for some reason.

**Comment by richmccartney** [comment]
Here is the tooltip style I did in MAAS if you want to see as a reference 

```
.tooltip {
  position: relative;

  &::before {
    content: attr(data-tooltip) ;
    font-size: 13px;
    font-weight: 400;
    position:absolute;
    z-index: 999;
    white-space:nowrap;
    left: 50%;
    -webkit-transform: translateX(-50%);
    -ms-transform: translateX(-50%);
    transform: translateX(-50%);
    background:#333;
    color:#FFF;
    padding: 10px;
    text-indent: 0;
    opacity: 0;
    transition:opacity 0.4s ease-out;
    border-radius: 5px;
    box-shadow: 0px 1px 3px 0 rgba(51,51,51,0.2);
    top: -9999em;
  }

  &::after {
    position: absolute;
    left: 50%;
    -webkit-transform: translateX(-50%);
    -ms-transform: translateX(-50%);
    transform: translateX(-50%);
    content: '';
    width: 0;
    height: 0;
    border-left: 5px solid transparent;
    border-right: 5px solid transparent;
    z-index: 1000;

    transition:opacity 0.4s ease-out;

    border-top: 5px solid #333;
    opacity: 0;
    top: -9999em;
  }


  &:hover::before {
    opacity: 1 !important;
    top: -47px;
  }

  &:hover::after {
    opacity: 1 !important;
    top: -10px;
  }
}
```

**Comment by anthonydillon** [comment]
I agree the code could be improved. I wonder if it's OK as is and the component can be improved later? To change it I would need to change all the tooltips in jujucharms. Happy to but short on time at the moment.

**Comment by richmccartney** [comment]
@anthonydillon +1 to land.. We should make a few issues just to follow up on what we know we need to refactor in the future.

**Pull request merged**
